In [1]:
import torch
import numpy as np

In [2]:
a = torch.tensor([[1.0,2.0,3.0],
              [2.0,2.0,2.0],
              [3.0,3.0,3.0]], requires_grad=True)

print('cumsum', a.cumsum(axis=1))

def cs(a):
    return a.cumsum(axis=1).sum()

cumsum tensor([[1., 3., 6.],
        [2., 4., 6.],
        [3., 6., 9.]], grad_fn=<CumsumBackward0>)


In [3]:
f = cs(a)
f.backward()
a.grad

tensor([[3., 2., 1.],
        [3., 2., 1.],
        [3., 2., 1.]])

In [4]:
y = torch.tensor([ # has to be fully dimensional for all scenarios
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])

b = torch.tensor([  [1.0,2.0,3.0],
                    [2.0,2.0,2.0],
                    [3.0,3.0,3.0]], requires_grad=True)
c = b.cumsum(axis=1)
print(c)
print(y.transpose(0,1))
c.matmul(y.transpose(0,1))

tensor([[1., 3., 6.],
        [2., 4., 6.],
        [3., 6., 9.]], grad_fn=<CumsumBackward0>)
tensor([[1., 0., 0.],
        [0., 1., 1.],
        [0., 0., 0.]])


tensor([[1., 3., 3.],
        [2., 4., 4.],
        [3., 6., 6.]], grad_fn=<MmBackward0>)

In [5]:
b = torch.tensor([  [1.0,2.0,3.0],
                    [2.0,2.0,2.0],
                    [3.0,3.0,3.0]], requires_grad=True)
y = torch.tensor([ # has to be fully dimensional for all scenarios
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])

def cmatmul(b,y):
    c = b.cumsum(axis=1)
    return c.matmul(y.transpose(0,1)).sum()

f = cmatmul(b,y)
f.backward()
b.grad

tensor([[3., 2., 0.],
        [3., 2., 0.],
        [3., 2., 0.]])

In [6]:
torch.tensor([[1., 0., 0.],
        [0., 1., 1.],
        [0., 0., 0.]])

tensor([[1., 0., 0.],
        [0., 1., 1.],
        [0., 0., 0.]])

In [8]:
b = torch.tensor([  [1.0,2.0,3.0],
                    [2.0,2.0,2.0],
                    [3.0,3.0,3.0]], requires_grad=True)
y = torch.tensor([ # has to be fully dimensional for all scenarios
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])

def cmatmul(b,y):
    c = b.cumsum(axis=1)
    return c.matmul(y.transpose(0,1)).sum()

var = cmatmul(b,y)
var.backward()
b.grad

tensor([[3., 2., 0.],
        [3., 2., 0.],
        [3., 2., 0.]])

In [9]:
a = np.array([[3., 2., 1.],
        [3., 2., 1.],
        [3., 2., 1.]])

b = np.array([ # has to be fully dimensional for all scenarios
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])

a@b.T

array([[3., 2., 2.],
       [3., 2., 2.],
       [3., 2., 2.]])

In [ ]:
b = np.array([  [1.0,2.0,3.0,0.0],
                    [2.0,2.0,2.0, 0.0],
                    [3.0,3.0,3.0,0.0]])

c = b.cumsum(axis=1)
f = np.zeros((b.shape[0],b.shape[1]))
diag= []
for i in range(b.shape[0]):
    for j in range(b.shape[1]):
        if i==j:
            diag.append(c[i,j])
        if i!=j:
            f[i,j] = c[i,j]

f

array([[0., 3., 6., 6.],
       [2., 0., 6., 6.],
       [3., 6., 0., 9.]])

In [ ]:
diag

[1.0, 4.0, 9.0]